defmodule KinoWebBluetooth.Spec do
  @moduledoc """
  Tracks which requirements of the spec are implemented.

  Requirements are read from `spec/kino_web_bluetooth.spec.md`. A
  requirement counts as implemented when:

    * tests tagged with its ID pass, for example
      `@tag spec: "UI-4"` or `@describetag spec: ["API-3", "API-4"]`, or
    * it has a review in `spec/reviews.exs`, for requirements that
      tests can't fully cover

  `mix spec` runs the tests and writes the result to `spec/STATUS.md`.
  """

  @spec_path "spec/kino_web_bluetooth.spec.md"
  @reviews_path "spec/reviews.exs"
  @status_path "spec/STATUS.md"

  def status_path, do: @status_path

  @doc """
  Returns the requirements as `%{id, section, text}` maps, in spec order.

  Raises if an ID is used twice.
  """
  def requirements(path \\ @spec_path) do
    {requirements, _section} =
      path
      |> File.read!()
      |> String.split("\n")
      |> Enum.reduce({[], nil}, fn line, {requirements, section} ->
        cond do
          match = Regex.run(~r/^##\s+(.+?)\s*$/, line) ->
            {requirements, Enum.at(match, 1)}

          match = Regex.run(~r/^-\s+\[([A-Z]+-\d+)\]\s+(.+?)\s*$/, line) ->
            [_, id, text] = match
            {[%{id: id, section: section, text: text} | requirements], section}

          true ->
            {requirements, section}
        end
      end)

    requirements = Enum.reverse(requirements)

    case requirements |> Enum.frequencies_by(& &1.id) |> Enum.filter(&(elem(&1, 1) > 1)) do
      [] -> requirements
      duplicates -> raise "duplicate requirement IDs: #{inspect(Keyword.keys(duplicates))}"
    end
  end

  @doc "Returns the reviews as a map of requirement ID to note."
  def reviews(path \\ @reviews_path) do
    {reviews, _binding} = Code.eval_file(path)
    reviews
  end

  @doc """
  Combines requirements with test results and reviews.

  `results` maps requirement IDs to the results of their tests
  (`:passed`, `:failed` or `:skipped`).
  """
  def status(requirements, results, reviews) do
    for requirement <- requirements do
      tests = Map.get(results, requirement.id, [])
      review = Map.get(reviews, requirement.id)

      status =
        cond do
          :failed in tests -> :failing
          tests != [] and Enum.all?(tests, &(&1 == :passed)) -> :tested
          review -> :reviewed
          true -> :open
        end

      Map.merge(requirement, %{
        status: status,
        tests: Enum.count(tests, &(&1 == :passed)),
        review: review
      })
    end
  end

  @doc "Returns the IDs referenced by tests or reviews that are not in the spec."
  def unknown_ids(requirements, results, reviews) do
    known = MapSet.new(requirements, & &1.id)

    (Map.keys(results) ++ Map.keys(reviews))
    |> Enum.uniq()
    |> Enum.reject(&(&1 in known))
    |> Enum.sort()
  end

  @doc "Renders the status as Markdown."
  def render(statuses, unknown_ids) do
    counts = Enum.frequencies_by(statuses, & &1.status)

    sections =
      statuses
      |> Enum.chunk_by(& &1.section)
      |> Enum.map(fn [%{section: section} | _] = rows ->
        """
        ## #{section}

        | ID | Requirement | Status | Evidence |
        | --- | --- | --- | --- |
        #{Enum.map_join(rows, "\n", &row/1)}
        """
      end)

    warnings =
      if unknown_ids != [] do
        """

        ## ⚠️ Unknown IDs

        Tests or reviews refer to IDs that are not in the spec:
        #{Enum.join(unknown_ids, ", ")}.
        """
      end

    """
    # Spec status

    <!-- Generated by `mix spec`. Do not edit. -->

    Implementation status of [the spec](kino_web_bluetooth.spec.md):
    ✅ #{counts[:tested] || 0} tested,
    👀 #{counts[:reviewed] || 0} reviewed,
    ❌ #{counts[:failing] || 0} failing,
    ⬜ #{counts[:open] || 0} open.

    * ✅ **Tested**: covered by passing tests
    * 👀 **Reviewed**: checked by hand, see `spec/reviews.exs`
    * ❌ **Failing**: some of its tests fail
    * ⬜ **Open**: neither tested nor reviewed
    #{warnings}
    #{Enum.join(sections, "\n")}\
    """
  end

  defp row(status) do
    evidence =
      [
        status.tests > 0 && "#{status.tests} #{if status.tests == 1, do: "test", else: "tests"}",
        status.review
      ]
      |> Enum.filter(& &1)
      |> Enum.join("; ")

    "| #{status.id} | #{escape(status.text)} | #{icon(status.status)} | #{escape(evidence)} |"
  end

  defp icon(:tested), do: "✅ Tested"
  defp icon(:reviewed), do: "👀 Reviewed"
  defp icon(:failing), do: "❌ Failing"
  defp icon(:open), do: "⬜ Open"

  defp escape(text), do: String.replace(text, "|", "\\|")
end
